import { renderEvents } from "./components/EventsRow.js"; // Import the renderEvents function
import { renderHeader } from "./components/Header.js";

const dummyEvents = [
  // Dummy data for events generated by ChatGPT
  {
    id: 1,
    name: "The Pint Public House",
    image: "../images/dummyImage.jpg",
    registration: "180 Fans Going",
    date: "June 18, 2026 • 11:00 AM",
    description:
      "Brazil vs Germany live on giant screens. Game-day brunch and drink specials available.",
  },
  {
    id: 2,
    name: "Shark Club Sports Bar",
    image: "../images/dummyImage.jpg",
    registration: "240 Fans Going",
    date: "June 22, 2026 • 2:00 PM",
    description:
      "Canada vs Mexico with full sound, themed cocktails, and halftime giveaways.",
  },
  {
    id: 3,
    name: "Tap & Barrel • Olympic Village",
    image: "../images/dummyImage.jpg",
    registration: "95 Fans Going",
    date: "June 25, 2026 • 5:30 PM",
    description:
      "Patio screening for Argentina vs France. Craft beer and shareable plates.",
  },
  {
    id: 4,
    name: "The Sportsbar LIVE! at Rogers Arena",
    image: "../images/dummyImage.jpg",
    registration: "320 Fans Going",
    date: "June 30, 2026 • 12:00 PM",
    description:
      "England vs Spain on the big screen with stadium vibes and prize draws.",
  },
];

function sayHello() {}
// document.addEventListener('DOMContentLoaded', sayHello);

function setup() {
  // render the dummy data into the page
  renderEvents(dummyEvents, "happening-this-week");
  renderEvents(dummyEvents, "popular-events");
  renderEvents(dummyEvents, "near-you-events");
  // render header and all sub-components
  renderHeader("header");
}

$(document).ready(function () {
  setup();
});
